# Generated by Django 5.2.14 on 2026-05-25 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('natural', 'Persona natural'), ('company', 'Empresa'), ('government', 'Institucion'), ('other', 'Otro')], default='natural', max_length=20, verbose_name='tipo de cliente')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('address', models.TextField(blank=True, verbose_name='direccion')),
                ('ruc', models.CharField(blank=True, max_length=30, verbose_name='RUC')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['whatsapp'], name='customers_c_whatsap_11d95c_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['ruc'], name='customers_c_ruc_e5305e_idx')],
            },
        ),
    ]
