# Generated by Django 5.2.14 on 2026-05-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('address', models.TextField(blank=True, verbose_name='direccion')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='ubicacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='codigo interno')),
                ('barcode', models.CharField(blank=True, max_length=80, verbose_name='codigo de barras')),
                ('description', models.CharField(max_length=255, verbose_name='descripcion')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo sin IVA')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio venta sin IVA')),
                ('applies_iva', models.BooleanField(default=True, verbose_name='aplica IVA')),
                ('warranty', models.CharField(blank=True, max_length=160, verbose_name='garantia')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='imagen')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_price_update', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion de precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoria')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.product', verbose_name='producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.warehouse', verbose_name='bodega')),
            ],
            options={
                'verbose_name': 'stock de producto',
                'verbose_name_plural': 'stock de productos',
                'ordering': ['warehouse__name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='catalog_pro_code_31976d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='catalog_pro_barcode_58f8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='catalog_pro_descrip_7b75a8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='catalog_pro_model_df7b03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'warehouse')},
        ),
    ]
